version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:14
    container_name: meu_postgres
    environment:
      POSTGRES_USER: space
      POSTGRES_PASSWORD: space
      POSTGRES_DB: space
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/space
    container_name: meu_spring_boot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/space
      SPRING_DATASOURCE_USERNAME: space
      SPRING_DATASOURCE_PASSWORD: space
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    build:
      context: ./frontend/space
    container_name: meu_react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  gerador:
    build:
      context: ./rocket_generator
    container_name: gerador
    depends_on:
      - rabbitmq
    command: ["poetry", "run", "python", "rocket_generator/receiver.py"]

volumes:
  postgres_data:
