version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: meu_postgres
    environment:
      POSTGRES_USER: space
      POSTGRES_PASSWORD: space
      POSTGRES_DB: space
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
